drop database if exists test_sql;
create database test_sql character set = 'utf8' collate = 'utf8_general_ci';

use test_sql;

create table pays_iso(
    alpha3 char(3) primary key ,
    nom varchar(50)
    
);

insert into pays_iso(alpha3, nom) values
('AFG','Afghanistan'),
('ALB','Albanie'),
('DZA','Algerie'),
('AND','Andorre'),
('AGO','Angola'),
('ATG','Antigua-et-Barbuda'),
('ARG','Argentine'),
('ARM','Armenie'),
('AUS','Australie'),
('AUT','Autriche'),
('AZE','Azerbaïdjan'),
('BHS','Bahamas'),
('BHR','Bahreïn'),
('BGD','Bangladesh'),
('BRB','Barbade'),
('BLR','Biélorussie'),
('BEL','Belgique'),
('BLZ','Belize'),
('BEN','Benin'),
('BTN','Bhoutan'),
('BOL','Bolivie'),
('BIH','Bosnie-Herzegovine'),
('BRA','Bresil'),
('BRN','Brunei Darussalam'),
('BGR','Bulgarie'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('CPV','Cap-Vert'),
('KHM','Cambodge'),
('CMR','Cameroun'),
('CAN','Canada'),
('CAF','République centrafricaine'),
('TCD','Tchad'),
('CHL','Chili'),
('CHN','Chine'),
('COL','Colombie'),
('COM','Comores'),
('COG','Congo'),
('CRI','Costa Rica'),
('HRV','Croatie'),
('CUB','Cuba'),
('CYP','Chypre'),
('CZE','Republique tchèque'),
('DNK','Danemark'),
('DJI','Djibouti'),
('DMA','Dominique'),
('DOM','Republique dominicaine'),
('ECU','Equateur'),
('EGY','Egypte'),
('SLV','El Salvador'),
('GNQ','Guinee equatoriale'),
('ERI','Erythree'),
('EST','Estonie'),
('SWZ','Eswatini'),
('ETH','Éthiopie'),
('FJI','Fidji'),
('FIN','Finlande'),
('FRA','France'),
('GAB','Gabon'),
('GMB','Gambie'),
('GEO','Georgie'),
('DEU','Allemagne'),
('GHA','Ghana'),
('GRC','Grèce'),
('GRD','Grenade'),
('GTM','Guatemala'),
('GIN','Guinee'),
('GNB','Guinee-Bissau'),
('GUY','Guyana'),
('HTI','Haiti'),
('HND','Honduras'),
('HUN','Hongrie'),
('ISL','Islande'),
('IND','Inde'),
('IDN','Indonesie'),
('IRN','Iran'),
('IRQ','Irak'),
('IRL','Irlande'),
('ISR','Israel'),
('ITA','Italie'),
('JAM','Jamaique'),
('JPN','Japon'),
('JOR','Jordanie'),
('KAZ','Kazakhstan'),
('KEN','Kenya'),
('KIR','Kiribati'),
('PRK','Coree du Nord'),
('KOR','Coree du Sud'),
('KWT','Koweit'),
('KGZ','Kirghizistan'),
('LAO','Laos'),
('LVA','Lettonie'),
('LBN','Liban'),
('LSO','Lesotho'),
('LBR','Liberia'),
('LBY','Libye'),
('LIE','Liechtenstein'),
('LTU','Lituanie'),
('LUX','Luxembourg'),
('MKD','Macedoine du Nord'),
('MDG','Madagascar'),
('MWI','Malawi'),
('MYS','Malaisie'),
('MDV','Maldives'),
('MLI','Mali'),
('MLT','Malte'),
('MHL','Iles Marshall'),
('MRT','Mauritanie'),
('MUS','Maurice'),
('MEX','Mexique'),
('FSM','Micronesie'),
('MDA','Moldavie'),
('MCO','Monaco'),
('MNG','Mongolie'),
('MNE','Montenegro'),
('MAR','Maroc'),
('MOZ','Mozambique'),
('MMR','Myanmar'),
('NAM','Namibie'),
('NRU','Nauru'),
('NPL','Nepal'),
('NLD','Pays-Bas'),
('NZL','Nouvelle-Zelande'),
('NIC','Nicaragua'),
('NER','Niger'),
('NGA','Nigeria'),
('NOR','Norvège'),
('OMN','Oman'),
('PAK','Pakistan'),
('PLW','Palaos'),
('PAN','Panama'),
('PNG','Papouasie-Nouvelle-Guinee'),
('PRY','Paraguay'),
('PER','Perou'),
('PHL','Philippines'),
('POL','Pologne'),
('PRT','Portugal'),
('QAT','Qatar'),
('ROU','Roumanie'),
('RUS','Russie'),
('RWA','Rwanda'),
('KNA','Saint-Christophe-et-Nieves'),
('LCA','Sainte-Lucie'),
('VCT','Saint-Vincent-et-les-Grenadines'),
('WSM','Samoa'),
('SMR','Saint-Marin'),
('STP','Sao Tome-et-Principe'),
('SAU','Arabie saoudite'),
('SEN','Senegal'),
('SRB','Serbie'),
('SYC','Seychelles'),
('SLE','Sierra Leone'),
('SGP','Singapour'),
('SVK','Slovaquie'),
('SVN','Slovénie'),
('SLB','Iles Salomon'),
('SOM','Somalie'),
('ZAF','Afrique du Sud'),
('SSD','Soudan du Sud'),
('ESP','Espagne'),
('LKA','Sri Lanka'),
('SDN','Soudan'),
('SUR','Suriname'),
('SWE','Suede'),
('CHE','Suisse'),
('SYR','Syrie'),
('TJK','Tadjikistan'),
('TZA','Tanzanie'),
('THA','Thailande'),
('TLS','Timor oriental'),
('TGO','Togo'),
('TON','Tonga'),
('TTO','Trinite-et-Tobago'),
('TUN','Tunisie'),
('TUR','Turquie'),
('TKM','Turkmenistan'),
('TUV','Tuvalu'),
('UGA','Ouganda'),
('UKR','Ukraine'),
('ARE','Emirats arabes unis'),
('GBR','Royaume-Uni'),
('USA','États-Unis'),
('URY','Uruguay'),
('UZB','Ouzbekistan'),
('VUT','Vanuatu'),
('VAT','Vatican'),
('VEN','Venezuela'),
('VNM','Vietnam'),
('YEM','Yemen'),
('ZMB','Zambie'),
('ZWE','Zimbabwe');

create table contacts(
    id int primary key auto_increment,
    nom varchar(50),
    pays varchar(50),
    foreign key (pays) references pays_iso(alpha3)
);

insert into contacts (nom, pays) values
("Dupont1","FRA"),
("Durand2","FRA"),
("Durand3","FRA"),
("Durand4","FRA"),
("Durand5","FRA"),
("Walter7","CHE"),
("Walter8","CHE"),
("Walter9","CHE"),
("Walter10","CHE");

insert into contacts (nom, pays) values
('Tony','ITA');

select * from contacts ;





